version: '3.7'

networks:
  budget:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '10.102.0.0/16'
services:
  db:
    image: mariadb
    hostname: db
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - budget
    ports:
      - '127.0.0.1:3306:3306'
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
  mailcatcher:
    image: schickling/mailcatcher:latest
    hostname: mailcatcher
    networks:
      budget:
        aliases:
          - mail.synevo.pl
    ports:
      - '127.0.0.1:1080:1080'
      - '127.0.0.1:1025:1025'
